server:
  port: 8081
spring:
  application:
    name: fraud
  datasource:
    username: 'amigoscode'
    password: 'password'
    url: jdbc:postgresql://192.168.99.100:5432/fraud
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: 'true'
    show-sql: 'true'
  zipkin:
    base-url: http://192.168.99.100:9411

eureka:
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka